require("configs.plugins.treesitter")
require("configs.plugins.catppuccin")
require("configs.plugins.telescope")
require("configs.plugins.lualine")
require("configs.plugins.mini")
require("configs.plugins.noice")
